# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-10 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('position', models.CharField(max_length=500)),
                ('commentary', models.CharField(max_length=500)),
                ('date_found', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncbi_entry', models.URLField()),
                ('date_extracted', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='virus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Virus'),
        ),
    ]
