# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-10 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virus',
            name='name',
            field=models.CharField(default='Virus', max_length=500),
        ),
        migrations.AlterField(
            model_name='location',
            name='position',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
