# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20171010_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='position',
            field=models.CharField(default='Someplace', max_length=500),
        ),
    ]
