# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20171010_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_conducted', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('position', models.CharField(max_length=500, null=True)),
                ('ncbi_entry', models.URLField()),
                ('genbank_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenomePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=10000)),
                ('is_mobile', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('commentary', models.CharField(max_length=500)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.Taxon')),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='virus',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Virus',
        ),
        migrations.AddField(
            model_name='genomepart',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Strain'),
        ),
        migrations.AddField(
            model_name='genomepart',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Taxon'),
        ),
        migrations.AddField(
            model_name='author',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Experiment'),
        ),
    ]
